[package]
name = "ws_test"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.54", features = [
    "Win32_System_Memory",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading"
] }
